/* Single icon family for the project: Tabler outline, via solid-icons.
   Import icons from here, never inline an SVG path at a call site. */
export {
  TbOutlineAdjustmentsHorizontal as FilterIcon,
  TbOutlineAlertCircle as AlertCircleIcon,
  TbOutlineAlertTriangle as WarningIcon,
  TbOutlineBrandGithub as GithubIcon,
  TbOutlineChartBar as ChartIcon,
  TbOutlineCheck as CheckIcon,
  TbOutlineChevronRight as ChevronRightIcon,
  TbOutlineClipboardText as ClipboardIcon,
  TbOutlineCopy as CopyIcon,
  TbOutlineDownload as DownloadIcon,
  TbOutlineEdit as EditIcon,
  TbOutlineExternalLink as ExternalLinkIcon,
  TbOutlineFileText as FileIcon,
  TbOutlineFlag as FlagIcon,
  TbOutlineInfoCircle as InfoIcon,
  TbOutlineLink as LinkIcon,
  TbOutlineLoader2 as SpinnerIcon,
  TbOutlineMenu2 as MenuIcon,
  TbOutlinePlus as PlusIcon,
  TbOutlinePrinter as PrintIcon,
  TbOutlineSearch as SearchIcon,
  TbOutlineUpload as UploadIcon,
  TbOutlineWorld as GlobeIcon,
  TbOutlineX as CloseIcon,
  TbOutlineZoomCancel as NoResultsIcon,
} from "solid-icons/tb";
